import {mkdirSync} from 'node:fs';
import {join} from 'node:path';
import {createServer} from './server.js';
import {createManager} from './manager.js';
import {openStore} from './store.js';
process.umask(0o077);
const key=process.env.API_KEY;if(!key||key.length<32)throw new Error('Configure API_KEY no .env (mínimo 32 caracteres)');
const dir=process.env.DATA_DIR||'./data';mkdirSync(dir,{recursive:true,mode:0o700});
const max=Number(process.env.MAX_INSTANCES||5);if(!Number.isInteger(max)||max<1||max>50)throw new Error('MAX_INSTANCES deve estar entre 1 e 50');
const days=Number(process.env.RETENTION_DAYS||30);if(!Number.isInteger(days)||days<1)throw new Error('RETENTION_DAYS inválido');
const store=openStore(join(dir,'zapi.sqlite'));
const manager=createManager({store,dir,max,meta:{token:process.env.META_ACCESS_TOKEN,version:process.env.META_GRAPH_VERSION}});
if(!manager.list().length)manager.create({id:'principal',provider:'qr'});
const server=createServer({key,manager,store,meta:{verifyToken:process.env.META_VERIFY_TOKEN,appSecret:process.env.META_APP_SECRET}});
store.prune(days);const prune=setInterval(()=>store.prune(days),86400000);prune.unref();
const host=process.env.HOST||'127.0.0.1',port=Number(process.env.PORT||3000);
server.listen(port,host,()=>console.log(`Painel: http://${host}:${port}`));
let stopping=false;
for(const signal of ['SIGINT','SIGTERM'])process.on(signal,()=>{if(stopping)return;stopping=true;clearInterval(prune);manager.close();server.close(()=>{store.close();process.exit(0);});setTimeout(()=>process.exit(0),5000).unref();});
